# Generated by Django 5.2 on 2025-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_skill_percentage_skill_level_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(default=70, help_text='Skill level as a percentage (0-100)'),
            preserve_default=False,
        ),
    ]
