# Generated by Django 5.2 on 2025-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_skill_level_skill_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome class (e.g., 'fab fa-html5')", max_length=100),
        ),
    ]
