# Generated by Django 5.2 on 2025-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_skill_level_alter_skill_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
