# Generated by Django 5.2 on 2025-04-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_skill_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_color',
            field=models.CharField(blank=True, default='#333', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_icon',
            field=models.CharField(blank=True, default='fab fa-github', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_color',
            field=models.CharField(blank=True, default='#0A66C2', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_icon',
            field=models.CharField(blank=True, default='fab fa-linkedin', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_color',
            field=models.CharField(blank=True, default='#1DA1F2', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_icon',
            field=models.CharField(blank=True, default='fab fa-twitter', max_length=100),
        ),
    ]
