# Generated by Django 5.2 on 2025-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_profile_github_color_profile_github_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_color',
            field=models.CharField(blank=True, default='#1877F2', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_icon',
            field=models.CharField(blank=True, default='fab fa-facebook-f', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_color',
            field=models.CharField(blank=True, default='#C13584', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_icon',
            field=models.CharField(blank=True, default='fab fa-instagram', max_length=100),
        ),
    ]
