# Generated by Django 5.2 on 2025-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_facebook_profile_facebook_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(default=70, max_length=100),
            preserve_default=False,
        ),
    ]
