# Generated by Django 5.2 on 2025-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_name_contactmessage_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
