# Generated by Django 5.1.7 on 2025-05-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram_color',
            field=models.CharField(blank=True, default='#C13584', max_length=100),
        ),
    ]
